import type { DashboardSummary } from "@/types/dashboard";

export const dashboardSummaryMock: DashboardSummary = {
  heroLabel: "Weekly command center",
  heroTitle: "Dashboard",
  heroDescription:
    "A premium read on trend direction, compliance pressure, and whether the body is moving the way the plan says it should.",
  kpis: [
    { label: "Day X / 75", value: "42 / 75", detail: "The challenge is deep enough now that consistency compounds.", tone: "primary" },
    { label: "Today completion", value: "62%", detail: "Five of eight non-negotiables are already closed.", tone: "secondary" },
    { label: "Current streak", value: "11 days", detail: "The clean run is alive. Protect the evening.", tone: "primary" },
    { label: "Perfect days", value: "28", detail: "Full-compliance days banked across the challenge." },
    { label: "Weight change", value: "-4.6 kg", detail: "Bodyweight trend since day one is moving cleanly.", tone: "secondary" },
    { label: "Calories today", value: "1,680", detail: "Still inside the day’s target envelope." },
    { label: "Protein today", value: "142 g", detail: "Protein is tracking well ahead of failure risk.", tone: "primary" },
    { label: "Water today", value: "2.6 L", detail: "A visible gap still needs to be closed." },
    { label: "Workout completion", value: "1 / 2", detail: "The second session still decides the day.", tone: "warning" },
    { label: "Outdoor status", value: "Pending", detail: "At least one workout must still happen outside.", tone: "warning" },
  ],
  trends: {
    weight: {
      title: "Weight trend",
      description: "Seven-day bodyweight trend against the cut phase.",
      unit: "kg",
      accent: "primary",
      summary: "Trending down without a sudden drop.",
      points: [
        { label: "Mon", value: 82.4 },
        { label: "Tue", value: 82.1 },
        { label: "Wed", value: 81.9 },
        { label: "Thu", value: 81.8 },
        { label: "Fri", value: 81.7 },
        { label: "Sat", value: 81.5 },
        { label: "Sun", value: 81.4 },
      ],
    },
    waist: {
      title: "Waist trend",
      description: "Waistline reduction is confirming the cut, not just scale movement.",
      unit: "cm",
      accent: "secondary",
      summary: "Down 1.8 cm over the current block.",
      points: [
        { label: "Mon", value: 90.8 },
        { label: "Tue", value: 90.6 },
        { label: "Wed", value: 90.5 },
        { label: "Thu", value: 90.4 },
        { label: "Fri", value: 90.3 },
        { label: "Sat", value: 90.1 },
        { label: "Sun", value: 90.0 },
      ],
    },
    calories: {
      title: "Calories trend",
      description: "Daily intake against the deficit plan.",
      unit: "kcal",
      accent: "warning",
      summary: "Most days are landing inside target without aggressive under-eating.",
      points: [
        { label: "Mon", value: 2140 },
        { label: "Tue", value: 2010 },
        { label: "Wed", value: 2220 },
        { label: "Thu", value: 1980 },
        { label: "Fri", value: 2165 },
        { label: "Sat", value: 2080 },
        { label: "Sun", value: 1680 },
      ],
    },
    protein: {
      title: "Protein trend",
      description: "Protein consistency supports muscle retention during the cut.",
      unit: "g",
      accent: "primary",
      summary: "Protein has cleared target on five of the last seven days.",
      points: [
        { label: "Mon", value: 156 },
        { label: "Tue", value: 149 },
        { label: "Wed", value: 162 },
        { label: "Thu", value: 145 },
        { label: "Fri", value: 168 },
        { label: "Sat", value: 151 },
        { label: "Sun", value: 142 },
      ],
    },
    hydration: {
      title: "Hydration trend",
      description: "Water adherence across the current week.",
      unit: "L",
      accent: "secondary",
      summary: "Hydration is the main compliance leak on late evenings.",
      points: [
        { label: "Mon", value: 4.2 },
        { label: "Tue", value: 3.9 },
        { label: "Wed", value: 4.0 },
        { label: "Thu", value: 3.4 },
        { label: "Fri", value: 4.1 },
        { label: "Sat", value: 3.8 },
        { label: "Sun", value: 2.6 },
      ],
    },
    compliance: {
      title: "Compliance score",
      description: "Challenge execution trend across the week.",
      unit: "%",
      accent: "primary",
      summary: "Strong overall execution with minor hydration drag.",
      points: [
        { label: "Mon", value: 100 },
        { label: "Tue", value: 88 },
        { label: "Wed", value: 100 },
        { label: "Thu", value: 75 },
        { label: "Fri", value: 100 },
        { label: "Sat", value: 88 },
        { label: "Sun", value: 62 },
      ],
    },
  },
  workoutFrequencySummary: {
    totalSessions: 8,
    completedDays: ["Mon", "Tue", "Wed", "Fri", "Sat"],
    summary: "Five training days, eight sessions, and one missed evening slot so far.",
  },
  cardioMinutesSummary: {
    totalMinutes: 205,
    averageMinutes: 29,
    summary: "Outdoor walking is carrying the cardio load without spiking fatigue.",
  },
  recentPrs: [
    { id: "1", exercise: "Incline Dumbbell Press", value: "32.5 kg x 9", dateLabel: "2 days ago" },
    { id: "2", exercise: "Lat Pulldown", value: "75 kg x 10", dateLabel: "4 days ago" },
    { id: "3", exercise: "Romanian Deadlift", value: "95 kg x 8", dateLabel: "6 days ago" },
  ],
  weekSummary: [
    { label: "Meals on plan", value: "19 / 21", tone: "primary" },
    { label: "Outdoor sessions", value: "4", tone: "secondary" },
    { label: "Average sleep", value: "6h 58m" },
    { label: "Recovery risk", value: "Moderate", tone: "warning" },
  ],
  nextPlannedWorkout: {
    title: "Pull + outdoor incline walk",
    focus: "Lats, rear delts, biceps, then 45 minutes outside",
    time: "Today, 7:15 PM",
    note: "The second session should stay low-friction. Clothes out, bottle full, route decided before 6 PM.",
  },
};
