"""Seed data for recipes, diet templates, and quick-add nutrition presets."""

from __future__ import annotations

import json

USER_PROFILE_DEFAULT = {
    "age": 27,
    "gender": "male",
    "height_cm": 175.0,
    "current_weight_kg": 83.5,
    "activity_level": "moderately_active",
    "goal": "fat_loss",
    "desired_deficit": 450,
}


def _json(data):
    return json.dumps(data)


RECIPE_LIBRARY = [
    {
        "recipe_name": "Beast Life Whey Protein",
        "meal_type": "post_workout",
        "ingredients_json": _json([{"item": "Beast Life Whey Protein", "quantity": "1 scoop"}, {"item": "Water", "quantity": "250 ml"}]),
        "steps_json": _json(["Add water to shaker.", "Add one scoop whey.", "Shake well and drink."]),
        "calories": 120,
        "protein": 24,
        "carbs": 3,
        "fats": 2,
        "fiber": 0,
        "portion_note": "1 scoop",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Banana 100 g",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Banana", "quantity": "100 g"}]),
        "steps_json": _json(["Peel and eat 20 to 30 minutes before training."]),
        "calories": 89,
        "protein": 1.1,
        "carbs": 23,
        "fats": 0.3,
        "fiber": 2.6,
        "portion_note": "100 g banana",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Banana Half",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Banana", "quantity": "1/2 medium"}]),
        "steps_json": _json(["Peel and eat as a light pre-workout option."]),
        "calories": 50,
        "protein": 0.6,
        "carbs": 13,
        "fats": 0.2,
        "fiber": 1.5,
        "portion_note": "1/2 banana",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Almonds 5",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Almonds", "quantity": "5 whole"}]),
        "steps_json": _json(["Measure 5 almonds and eat with water."]),
        "calories": 35,
        "protein": 1.3,
        "carbs": 1.2,
        "fats": 3,
        "fiber": 0.7,
        "portion_note": "5 almonds",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Dates 2",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Dates", "quantity": "2 whole"}]),
        "steps_json": _json(["Eat 2 dates before training for a quick carb boost."]),
        "calories": 46,
        "protein": 0.4,
        "carbs": 12,
        "fats": 0,
        "fiber": 1.3,
        "portion_note": "2 dates",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Black Coffee",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Black coffee", "quantity": "1 cup"}]),
        "steps_json": _json(["Brew and drink plain before training."]),
        "calories": 5,
        "protein": 0,
        "carbs": 0,
        "fats": 0,
        "fiber": 0,
        "portion_note": "1 cup",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Lemon Water",
        "meal_type": "pre_workout",
        "ingredients_json": _json([{"item": "Water", "quantity": "300 ml"}, {"item": "Lemon juice", "quantity": "1 tbsp"}]),
        "steps_json": _json(["Mix lemon juice into water and drink fresh."]),
        "calories": 6,
        "protein": 0,
        "carbs": 2,
        "fats": 0,
        "fiber": 0,
        "portion_note": "1 glass",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Dhokla 3 pcs + Curd",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Dhokla", "quantity": "3 pcs"}, {"item": "Hung curd", "quantity": "100 g"}]),
        "steps_json": _json(["Plate 3 dhokla pieces.", "Serve with 100 g curd on the side to raise protein."]),
        "calories": 280,
        "protein": 14,
        "carbs": 34,
        "fats": 8,
        "fiber": 3,
        "portion_note": "3 pcs + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Poha 1 cup + Curd",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Poha", "quantity": "1 cup"}, {"item": "Hung curd", "quantity": "100 g"}]),
        "steps_json": _json(["Cook poha lightly with peas and onion.", "Serve with curd to improve protein."]),
        "calories": 320,
        "protein": 13,
        "carbs": 46,
        "fats": 9,
        "fiber": 4,
        "portion_note": "1 cup + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Veg Omelette 3 Eggs",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Eggs", "quantity": "3"}, {"item": "Onion + tomato + capsicum", "quantity": "80 g"}, {"item": "Oil", "quantity": "1 tsp"}]),
        "steps_json": _json(["Whisk eggs with chopped vegetables.", "Cook as an omelette using minimal oil."]),
        "calories": 285,
        "protein": 21,
        "carbs": 5,
        "fats": 20,
        "fiber": 1.5,
        "portion_note": "3 eggs",
        "is_spicy": 0,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Oats Upma 1 cup + Whey Half Scoop",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Oats upma", "quantity": "1 cup"}, {"item": "Whey", "quantity": "1/2 scoop in water"}]),
        "steps_json": _json(["Cook oats upma with vegetables.", "Drink half scoop whey alongside for extra protein."]),
        "calories": 330,
        "protein": 18,
        "carbs": 42,
        "fats": 8,
        "fiber": 6,
        "portion_note": "1 cup + half scoop whey",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Idli 2 + Sambar + Curd",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Idli", "quantity": "2"}, {"item": "Sambar", "quantity": "1 cup"}, {"item": "Curd", "quantity": "75 g"}]),
        "steps_json": _json(["Serve hot idlis with sambar.", "Add curd on the side for protein."]),
        "calories": 295,
        "protein": 12,
        "carbs": 42,
        "fats": 7,
        "fiber": 5,
        "portion_note": "2 idli + sambar + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Appe 6 pcs + Curd",
        "meal_type": "breakfast",
        "ingredients_json": _json([{"item": "Appe", "quantity": "6 pcs"}, {"item": "Curd", "quantity": "100 g"}]),
        "steps_json": _json(["Serve appe hot.", "Add curd on the side to improve protein."]),
        "calories": 310,
        "protein": 12,
        "carbs": 40,
        "fats": 10,
        "fiber": 3,
        "portion_note": "6 pcs + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Bhakri + Dal + Veg + Curd",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Bhakri", "quantity": "1 medium"}, {"item": "Dal", "quantity": "1 cup"}, {"item": "Vegetable sabzi", "quantity": "1 cup"}, {"item": "Curd", "quantity": "100 g"}]),
        "steps_json": _json(["Serve bhakri with dal and sabzi.", "Add curd to raise meal protein."]),
        "calories": 510,
        "protein": 22,
        "carbs": 68,
        "fats": 14,
        "fiber": 12,
        "portion_note": "1 bhakri + dal + veg + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Rice + Varan + Curd",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Cooked rice", "quantity": "1 cup"}, {"item": "Varan", "quantity": "1 cup"}, {"item": "Curd", "quantity": "100 g"}]),
        "steps_json": _json(["Serve rice with varan.", "Add curd on the side for extra protein."]),
        "calories": 455,
        "protein": 18,
        "carbs": 68,
        "fats": 8,
        "fiber": 5,
        "portion_note": "1 cup rice + 1 cup varan + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Rice + Matki Usal + Curd",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Cooked rice", "quantity": "1 cup"}, {"item": "Matki usal", "quantity": "1 cup"}, {"item": "Curd", "quantity": "100 g"}]),
        "steps_json": _json(["Serve rice with matki usal.", "Add curd to improve protein and satiety."]),
        "calories": 500,
        "protein": 22,
        "carbs": 72,
        "fats": 9,
        "fiber": 10,
        "portion_note": "1 cup rice + 1 cup usal + curd",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Rice + Chana Usal + Curd",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Cooked rice", "quantity": "1 cup"}, {"item": "Chana usal", "quantity": "1 cup"}, {"item": "Curd", "quantity": "100 g"}]),
        "steps_json": _json(["Serve rice with chana usal.", "Add curd to raise protein."]),
        "calories": 520,
        "protein": 23,
        "carbs": 74,
        "fats": 10,
        "fiber": 11,
        "portion_note": "1 cup rice + 1 cup chana usal + curd",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Rice + Usal + Tak",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Cooked rice", "quantity": "1 cup"}, {"item": "Usal", "quantity": "1 cup"}, {"item": "Tak", "quantity": "1 glass"}]),
        "steps_json": _json(["Serve rice with usal.", "Drink tak with the meal."]),
        "calories": 470,
        "protein": 18,
        "carbs": 70,
        "fats": 8,
        "fiber": 8,
        "portion_note": "1 cup rice + usal + tak",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Bhakri + Veg + Curd",
        "meal_type": "lunch",
        "ingredients_json": _json([{"item": "Bhakri", "quantity": "1 medium"}, {"item": "Vegetable sabzi", "quantity": "1.5 cups"}, {"item": "Curd", "quantity": "150 g"}]),
        "steps_json": _json(["Serve bhakri with vegetable sabzi.", "Add curd to keep protein higher."]),
        "calories": 430,
        "protein": 14,
        "carbs": 55,
        "fats": 15,
        "fiber": 9,
        "portion_note": "1 bhakri + veg + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Fruit 150 g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Mixed fruit", "quantity": "150 g"}]),
        "steps_json": _json(["Wash, chop, and eat fresh."]),
        "calories": 85,
        "protein": 1,
        "carbs": 21,
        "fats": 0,
        "fiber": 3,
        "portion_note": "150 g fruit",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Fruit Bowl + Whey Half Scoop",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Mixed fruit", "quantity": "150 g"}, {"item": "Whey", "quantity": "1/2 scoop"}]),
        "steps_json": _json(["Prepare a fruit bowl.", "Drink half scoop whey on the side for protein."]),
        "calories": 145,
        "protein": 13,
        "carbs": 22,
        "fats": 1,
        "fiber": 3,
        "portion_note": "Fruit bowl + half scoop whey",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Roasted Chana 30 g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Roasted chana", "quantity": "30 g"}]),
        "steps_json": _json(["Measure and eat as a crunchy snack."]),
        "calories": 120,
        "protein": 6,
        "carbs": 18,
        "fats": 2,
        "fiber": 5,
        "portion_note": "30 g",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Makhana 30 g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Makhana", "quantity": "30 g"}, {"item": "Ghee", "quantity": "1/4 tsp"}, {"item": "Salt and pepper", "quantity": "to taste"}]),
        "steps_json": _json(["Dry roast or lightly toss in ghee.", "Season and serve."]),
        "calories": 110,
        "protein": 4,
        "carbs": 20,
        "fats": 2,
        "fiber": 2,
        "portion_note": "30 g",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Corn 1 cup",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Boiled sweet corn", "quantity": "1 cup"}]),
        "steps_json": _json(["Boil or steam corn.", "Season lightly and serve."]),
        "calories": 135,
        "protein": 5,
        "carbs": 29,
        "fats": 2,
        "fiber": 4,
        "portion_note": "1 cup",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Sprouts Chaat 1 cup",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Mixed sprouts", "quantity": "1 cup"}, {"item": "Onion + tomato + lemon", "quantity": "50 g"}]),
        "steps_json": _json(["Mix sprouts with onion, tomato, and lemon.", "Season and eat fresh."]),
        "calories": 165,
        "protein": 11,
        "carbs": 23,
        "fats": 3,
        "fiber": 7,
        "portion_note": "1 cup",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Fruit + Peanuts 15 g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Mixed fruit", "quantity": "150 g"}, {"item": "Peanuts", "quantity": "15 g"}]),
        "steps_json": _json(["Serve fruit with measured peanuts for satiety."]),
        "calories": 170,
        "protein": 5,
        "carbs": 22,
        "fats": 7,
        "fiber": 4,
        "portion_note": "Fruit + 15 g peanuts",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Roasted Corn",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Corn kernels", "quantity": "1 cup"}]),
        "steps_json": _json(["Roast or saute corn lightly and season."]),
        "calories": 140,
        "protein": 5,
        "carbs": 30,
        "fats": 2,
        "fiber": 4,
        "portion_note": "1 cup",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Besan Chilla 2 + Curd",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Besan chilla", "quantity": "2"}, {"item": "Curd", "quantity": "150 g"}]),
        "steps_json": _json(["Cook 2 besan chillas.", "Serve with curd to make the dinner more protein-forward."]),
        "calories": 345,
        "protein": 18,
        "carbs": 30,
        "fats": 14,
        "fiber": 6,
        "portion_note": "2 chilla + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Moong Chilla 2 + Curd",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Moong chilla", "quantity": "2"}, {"item": "Curd", "quantity": "150 g"}]),
        "steps_json": _json(["Cook 2 moong chillas.", "Serve with curd for better protein and satiety."]),
        "calories": 360,
        "protein": 20,
        "carbs": 34,
        "fats": 11,
        "fiber": 7,
        "portion_note": "2 chilla + curd",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Rice 3 Eggs + Half Cup Rice",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Eggs", "quantity": "3"}, {"item": "Cooked rice", "quantity": "1/2 cup"}, {"item": "Vegetables", "quantity": "80 g"}]),
        "steps_json": _json(["Scramble eggs with vegetables.", "Toss with half cup rice."]),
        "calories": 360,
        "protein": 22,
        "carbs": 22,
        "fats": 18,
        "fiber": 2,
        "portion_note": "3 eggs + 1/2 cup rice",
        "is_spicy": 1,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Bhurji + Rice",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Eggs", "quantity": "3"}, {"item": "Cooked rice", "quantity": "1/2 cup"}, {"item": "Onion tomato masala", "quantity": "80 g"}]),
        "steps_json": _json(["Make bhurji with 3 eggs.", "Serve with half cup rice."]),
        "calories": 380,
        "protein": 23,
        "carbs": 24,
        "fats": 20,
        "fiber": 2,
        "portion_note": "3 eggs + 1/2 cup rice",
        "is_spicy": 1,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Paneer Sandwich High Protein",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Whole wheat bread", "quantity": "2 slices"}, {"item": "Low-fat paneer", "quantity": "140 g"}, {"item": "Vegetables", "quantity": "50 g"}]),
        "steps_json": _json(["Stuff bread with paneer filling.", "Toast lightly and serve."]),
        "calories": 410,
        "protein": 28,
        "carbs": 28,
        "fats": 20,
        "fiber": 5,
        "portion_note": "2-slice sandwich",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Sandwich 3 Eggs",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Whole wheat bread", "quantity": "2 slices"}, {"item": "Eggs", "quantity": "3"}, {"item": "Vegetables", "quantity": "40 g"}]),
        "steps_json": _json(["Cook eggs and make a filling.", "Assemble in bread and toast if desired."]),
        "calories": 390,
        "protein": 24,
        "carbs": 24,
        "fats": 20,
        "fiber": 4,
        "portion_note": "2-slice sandwich",
        "is_spicy": 0,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Soya Biryani High Protein",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Soya chunks dry", "quantity": "60 g"}, {"item": "Cooked rice", "quantity": "1/2 cup"}, {"item": "Vegetables", "quantity": "100 g"}]),
        "steps_json": _json(["Cook soya chunks and spices.", "Toss with vegetables and half cup rice."]),
        "calories": 360,
        "protein": 28,
        "carbs": 30,
        "fats": 8,
        "fiber": 7,
        "portion_note": "60 g dry soya + 1/2 cup rice",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 1,
    },
    {
        "recipe_name": "Soya Bhurji + Rice",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Soya granules", "quantity": "60 g dry"}, {"item": "Cooked rice", "quantity": "1/2 cup"}, {"item": "Onion tomato masala", "quantity": "80 g"}]),
        "steps_json": _json(["Cook soya bhurji with masala.", "Serve with half cup rice."]),
        "calories": 340,
        "protein": 27,
        "carbs": 28,
        "fats": 7,
        "fiber": 7,
        "portion_note": "60 g dry soya + 1/2 cup rice",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 1,
    },
    {
        "recipe_name": "Dosa + Paneer",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Dosa", "quantity": "1 large"}, {"item": "Low-fat paneer filling", "quantity": "120 g"}]),
        "steps_json": _json(["Prepare dosa.", "Fill with paneer masala and fold."]),
        "calories": 390,
        "protein": 22,
        "carbs": 34,
        "fats": 17,
        "fiber": 3,
        "portion_note": "1 large dosa + paneer filling",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Dosa",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Dosa", "quantity": "1 large"}, {"item": "Eggs", "quantity": "2"}]),
        "steps_json": _json(["Spread beaten eggs over dosa while cooking.", "Fold and serve hot."]),
        "calories": 340,
        "protein": 18,
        "carbs": 28,
        "fats": 16,
        "fiber": 2,
        "portion_note": "1 large egg dosa",
        "is_spicy": 0,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Biryani 3 Eggs",
        "meal_type": "dinner",
        "ingredients_json": _json([{"item": "Eggs", "quantity": "3"}, {"item": "Cooked rice", "quantity": "1/2 cup"}, {"item": "Vegetables and spices", "quantity": "100 g"}]),
        "steps_json": _json(["Cook eggs with biryani masala.", "Mix with vegetables and half cup rice."]),
        "calories": 400,
        "protein": 24,
        "carbs": 30,
        "fats": 19,
        "fiber": 3,
        "portion_note": "3 eggs + 1/2 cup rice",
        "is_spicy": 1,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Spicy Sprouts Chaat",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Mixed sprouts", "quantity": "150 g"}, {"item": "Onion", "quantity": "30 g"}, {"item": "Tomato", "quantity": "30 g"}, {"item": "Green chutney", "quantity": "1 tbsp"}]),
        "steps_json": _json(["Mix everything and season well."]),
        "calories": 180,
        "protein": 12,
        "carbs": 24,
        "fats": 3,
        "fiber": 7,
        "portion_note": "1 spicy bowl",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Masala Roasted Chana",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Roasted chana", "quantity": "50 g"}, {"item": "Masala seasoning", "quantity": "1 tsp"}]),
        "steps_json": _json(["Toss and serve."]),
        "calories": 190,
        "protein": 10,
        "carbs": 28,
        "fats": 4,
        "fiber": 8,
        "portion_note": "50 g pack",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Paneer Tikka 100g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Low-fat paneer", "quantity": "100 g"}, {"item": "Tikka marinade", "quantity": "2 tbsp"}]),
        "steps_json": _json(["Marinate and grill paneer."]),
        "calories": 220,
        "protein": 18,
        "carbs": 6,
        "fats": 14,
        "fiber": 1,
        "portion_note": "100 g paneer tikka",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Egg Bhurji 2 eggs",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Eggs", "quantity": "2"}, {"item": "Onion-tomato masala", "quantity": "50 g"}]),
        "steps_json": _json(["Cook bhurji and serve hot."]),
        "calories": 210,
        "protein": 14,
        "carbs": 5,
        "fats": 14,
        "fiber": 1,
        "portion_note": "2 eggs",
        "is_spicy": 1,
        "is_vegetarian": 0,
        "is_egg_based": 1,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Soya Chunks Masala 50g",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Soya chunks", "quantity": "50 g dry"}, {"item": "Masala", "quantity": "to taste"}]),
        "steps_json": _json(["Boil, squeeze, and saute with masala."]),
        "calories": 175,
        "protein": 26,
        "carbs": 12,
        "fats": 2,
        "fiber": 5,
        "portion_note": "50 g dry soya cooked",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 1,
    },
    {
        "recipe_name": "Peanut Masala",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Roasted peanuts", "quantity": "35 g"}, {"item": "Onion and coriander", "quantity": "30 g"}]),
        "steps_json": _json(["Mix and serve."]),
        "calories": 230,
        "protein": 9,
        "carbs": 10,
        "fats": 18,
        "fiber": 4,
        "portion_note": "1 small bowl",
        "is_spicy": 1,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
    {
        "recipe_name": "Whey Cold Coffee",
        "meal_type": "snack",
        "ingredients_json": _json([{"item": "Whey", "quantity": "1 scoop"}, {"item": "Instant coffee", "quantity": "1 tsp"}, {"item": "Skim milk", "quantity": "200 ml"}]),
        "steps_json": _json(["Blend all ingredients with ice."]),
        "calories": 170,
        "protein": 26,
        "carbs": 9,
        "fats": 3,
        "fiber": 0,
        "portion_note": "1 tall glass",
        "is_spicy": 0,
        "is_vegetarian": 1,
        "is_egg_based": 0,
        "is_soya_based": 0,
    },
]


DIET_PLAN_TEMPLATES = [
    ("Monday", "pre_workout", "Banana 100 g", "Almonds 5", "Black Coffee", "Dates 2", "Egg-free day"),
    ("Monday", "breakfast", "Dhokla 3 pcs + Curd", "Poha 1 cup + Curd", "Idli 2 + Sambar + Curd", "Oats Upma 1 cup + Whey Half Scoop", ""),
    ("Monday", "lunch", "Bhakri + Dal + Veg + Curd", "Rice + Varan + Curd", "Rice + Matki Usal + Curd", "Rice + Chana Usal + Curd", ""),
    ("Monday", "snack", "Roasted Chana 30 g", "Fruit 150 g", "Sprouts Chaat 1 cup", "Makhana 30 g", ""),
    ("Monday", "dinner", "Besan Chilla 2 + Curd", "Moong Chilla 2 + Curd", "Paneer Sandwich High Protein", "Dosa + Paneer", "No chapati at dinner"),
    ("Tuesday", "pre_workout", "Dates 2", "Black Coffee", "Banana 100 g", "Almonds 5", ""),
    ("Tuesday", "breakfast", "Veg Omelette 3 Eggs", "Oats Upma 1 cup + Whey Half Scoop", "Poha 1 cup + Curd", "Dhokla 3 pcs + Curd", ""),
    ("Tuesday", "lunch", "Rice + Matki Usal + Curd", "Bhakri + Dal + Veg + Curd", "Rice + Varan + Curd", "Rice + Chana Usal + Curd", ""),
    ("Tuesday", "snack", "Fruit 150 g", "Makhana 30 g", "Roasted Chana 30 g", "Fruit + Peanuts 15 g", ""),
    ("Tuesday", "dinner", "Egg Rice 3 Eggs + Half Cup Rice", "Egg Bhurji + Rice", "Egg Sandwich 3 Eggs", "Egg Dosa", "No chapati at dinner"),
    ("Wednesday", "pre_workout", "Banana Half", "Almonds 5", "Black Coffee", "Dates 2", ""),
    ("Wednesday", "breakfast", "Poha 1 cup + Curd", "Dhokla 3 pcs + Curd", "Veg Omelette 3 Eggs", "Idli 2 + Sambar + Curd", ""),
    ("Wednesday", "lunch", "Bhakri + Dal + Veg + Curd", "Rice + Matki Usal + Curd", "Rice + Varan + Curd", "Rice + Chana Usal + Curd", ""),
    ("Wednesday", "snack", "Corn 1 cup", "Sprouts Chaat 1 cup", "Roasted Corn", "Fruit 150 g", ""),
    ("Wednesday", "dinner", "Paneer Sandwich High Protein", "Egg Sandwich 3 Eggs", "Dosa + Paneer", "Egg Dosa", "No chapati at dinner"),
    ("Thursday", "pre_workout", "Lemon Water", "Dates 2", "Black Coffee", "Almonds 5", "Egg-free day"),
    ("Thursday", "breakfast", "Idli 2 + Sambar + Curd", "Poha 1 cup + Curd", "Dhokla 3 pcs + Curd", "Oats Upma 1 cup + Whey Half Scoop", ""),
    ("Thursday", "lunch", "Rice + Chana Usal + Curd", "Bhakri + Dal + Veg + Curd", "Rice + Varan + Curd", "Rice + Matki Usal + Curd", ""),
    ("Thursday", "snack", "Fruit 150 g", "Roasted Chana 30 g", "Makhana 30 g", "Fruit + Peanuts 15 g", ""),
    ("Thursday", "dinner", "Moong Chilla 2 + Curd", "Besan Chilla 2 + Curd", "Paneer Sandwich High Protein", "Dosa + Paneer", "No chapati at dinner"),
    ("Friday", "pre_workout", "Black Coffee", "Banana 100 g", "Dates 2", "Almonds 5", "Soya day"),
    ("Friday", "breakfast", "Dhokla 3 pcs + Curd", "Veg Omelette 3 Eggs", "Poha 1 cup + Curd", "Oats Upma 1 cup + Whey Half Scoop", ""),
    ("Friday", "lunch", "Bhakri + Dal + Veg + Curd", "Rice + Varan + Curd", "Rice + Matki Usal + Curd", "Rice + Chana Usal + Curd", ""),
    ("Friday", "snack", "Fruit + Peanuts 15 g", "Makhana 30 g", "Roasted Chana 30 g", "Sprouts Chaat 1 cup", ""),
    ("Friday", "dinner", "Soya Biryani High Protein", "Soya Bhurji + Rice", "Dosa + Paneer", "Moong Chilla 2 + Curd", "No chapati at dinner"),
    ("Saturday", "pre_workout", "Dates 2", "Almonds 5", "Black Coffee", "Banana 100 g", ""),
    ("Saturday", "breakfast", "Veg Omelette 3 Eggs", "Oats Upma 1 cup + Whey Half Scoop", "Dhokla 3 pcs + Curd", "Poha 1 cup + Curd", ""),
    ("Saturday", "lunch", "Rice + Usal + Tak", "Bhakri + Veg + Curd", "Bhakri + Dal + Veg + Curd", "Rice + Chana Usal + Curd", ""),
    ("Saturday", "snack", "Roasted Corn", "Fruit 150 g", "Roasted Chana 30 g", "Fruit + Peanuts 15 g", ""),
    ("Saturday", "dinner", "Dosa + Paneer", "Egg Dosa", "Paneer Sandwich High Protein", "Egg Sandwich 3 Eggs", "No chapati at dinner"),
    ("Sunday", "pre_workout", "Banana Half", "Dates 2", "Black Coffee", "Almonds 5", ""),
    ("Sunday", "breakfast", "Appe 6 pcs + Curd", "Idli 2 + Sambar + Curd", "Poha 1 cup + Curd", "Dhokla 3 pcs + Curd", ""),
    ("Sunday", "lunch", "Bhakri + Dal + Veg + Curd", "Rice + Matki Usal + Curd", "Rice + Chana Usal + Curd", "Rice + Varan + Curd", ""),
    ("Sunday", "snack", "Fruit Bowl + Whey Half Scoop", "Roasted Chana 30 g", "Fruit 150 g", "Sprouts Chaat 1 cup", ""),
    ("Sunday", "dinner", "Egg Biryani 3 Eggs", "Egg Rice 3 Eggs + Half Cup Rice", "Egg Bhurji + Rice", "Egg Dosa", "No chapati at dinner"),
]


SPICY_SNACK_NAMES = [
    "Spicy Sprouts Chaat",
    "Masala Roasted Chana",
    "Paneer Tikka 100g",
    "Egg Bhurji 2 eggs",
    "Soya Chunks Masala 50g",
    "Peanut Masala",
    "Whey Cold Coffee",
]
