"""Exercise seed data for the fitness tracker app."""

EXERCISES = [
    # Chest / Push
    ("Flat Dumbbell Press", "Push", "Chest"),
    ("Flat Barbell Bench Press", "Push", "Chest"),
    ("Incline Dumbbell Press", "Push", "Upper Chest"),
    ("Incline Barbell Bench Press", "Push", "Upper Chest"),
    ("Incline Machine Press", "Push", "Upper Chest"),
    ("Chest Press Machine", "Push", "Chest"),
    ("Smith Machine Press", "Push", "Chest"),
    ("Pec Deck Fly", "Push", "Chest"),
    ("Cable Fly", "Push", "Chest"),
    ("High to Low Cable Crossover", "Push", "Lower Chest"),
    ("Low to High Cable Fly", "Push", "Upper Chest"),
    ("Push-ups", "Push", "Chest"),
    ("Weighted Push-ups", "Push", "Chest"),
    ("Dips", "Push", "Lower Chest"),
    # Shoulders
    ("Shoulder Press", "Push", "Front Delts"),
    ("Dumbbell Shoulder Press", "Push", "Front Delts"),
    ("Machine Shoulder Press", "Push", "Front Delts"),
    ("Arnold Press", "Push", "Front Delts"),
    ("Cable Lateral Raise", "Push", "Side Delts"),
    ("Dumbbell Lateral Raise", "Push", "Side Delts"),
    ("Front Raise", "Push", "Front Delts"),
    ("Reverse Pec Deck", "Pull", "Rear Delts"),
    ("Face Pull", "Pull", "Rear Delts"),
    ("Rear Delt Fly", "Pull", "Rear Delts"),
    ("Upright Row", "Pull", "Traps"),
    # Triceps
    ("Rope Pushdown", "Push", "Triceps"),
    ("Straight Bar Pushdown", "Push", "Triceps"),
    ("Overhead Rope Extension", "Push", "Triceps"),
    ("Skull Crushers", "Push", "Triceps"),
    ("Cable Tricep Skull Crusher", "Push", "Triceps"),
    ("Close Grip Bench Press", "Push", "Triceps"),
    ("Bench Dips", "Push", "Triceps"),
    # Back / Lats
    ("Lat Pulldown", "Pull", "Lats"),
    ("Wide Grip Lat Pulldown", "Pull", "Lats"),
    ("Close Grip Lat Pulldown", "Pull", "Lats"),
    ("Pull-ups", "Pull", "Lats"),
    ("Assisted Pull-ups", "Pull", "Lats"),
    ("Seated Cable Row", "Pull", "Back"),
    ("Seated Machine Row Wide Grip", "Pull", "Upper Back"),
    ("Seated Machine Row Close Grip", "Pull", "Back"),
    ("Barbell Row", "Pull", "Back"),
    ("T-Bar Row", "Pull", "Upper Back"),
    ("Dumbbell Row", "Pull", "Back"),
    ("Chest Supported Row", "Pull", "Upper Back"),
    ("Straight Arm Pulldown", "Pull", "Lats"),
    ("Shrugs", "Pull", "Traps"),
    # Biceps / forearms
    ("Dumbbell Curl", "Pull", "Biceps"),
    ("Alternating Dumbbell Curl", "Pull", "Biceps"),
    ("Machine Curl", "Pull", "Biceps"),
    ("Hammer Curl", "Pull", "Biceps"),
    ("Preacher Curl", "Pull", "Biceps"),
    ("Cable Curl", "Pull", "Biceps"),
    ("Bayesian Curl", "Pull", "Biceps"),
    ("Concentration Curl", "Pull", "Biceps"),
    ("EZ Bar Curl", "Pull", "Biceps"),
    ("Wrist Curl", "Pull", "Forearms"),
    ("Reverse Wrist Curl", "Pull", "Forearms"),
    # Legs
    ("Squat", "Legs", "Quads"),
    ("Back Squat", "Legs", "Quads"),
    ("Front Squat", "Legs", "Quads"),
    ("Smith Machine Squat", "Legs", "Quads"),
    ("Squat Machine", "Legs", "Quads"),
    ("Leg Press", "Legs", "Quads"),
    ("Leg Extension", "Legs", "Quads"),
    ("Romanian Deadlift", "Legs", "Hamstrings"),
    ("Barbell RDL", "Legs", "Hamstrings"),
    ("Dumbbell RDL", "Legs", "Hamstrings"),
    ("Leg Curl", "Legs", "Hamstrings"),
    ("Seated Leg Curl", "Legs", "Hamstrings"),
    ("Lying Leg Curl", "Legs", "Hamstrings"),
    ("Bulgarian Split Squat", "Legs", "Glutes"),
    ("Walking Lunges", "Legs", "Glutes"),
    ("Hip Thrust", "Legs", "Glutes"),
    ("Glute Bridge", "Legs", "Glutes"),
    ("Calf Raises", "Legs", "Calves"),
    ("Seated Calf Raise", "Legs", "Calves"),
    ("Standing Calf Raise", "Legs", "Calves"),
    # Core
    ("Crunches", "Full Body", "Abs"),
    ("Cable Crunch", "Full Body", "Abs"),
    ("Hanging Leg Raise", "Full Body", "Abs"),
    ("Plank", "Full Body", "Abs"),
    ("Russian Twists", "Full Body", "Obliques"),
    ("Ab Wheel", "Full Body", "Abs"),
    ("Mountain Climbers", "Full Body", "Full Body"),
    ("Dead Bug", "Full Body", "Abs"),
    ("Pallof Press", "Full Body", "Obliques"),
    # Cardio
    ("Treadmill Running", "Cardio", "Cardio"),
    ("Incline Walking", "Cardio", "Cardio"),
    ("Cycling", "Cardio", "Cardio"),
    ("Stairmaster", "Cardio", "Cardio"),
    ("Rowing Machine", "Cardio", "Cardio"),
    ("Elliptical", "Cardio", "Cardio"),
    ("Jump Rope", "Cardio", "Cardio"),
    ("Outdoor Walk", "Cardio", "Cardio"),
    ("Outdoor Run", "Cardio", "Cardio"),
    ("Sled Push", "Full Body", "Full Body"),
    # Upper / Lower variants
    ("Cable Row", "Upper", "Back"),
    ("Bench Press", "Upper", "Chest"),
    ("Pull Down", "Upper", "Lats"),
    ("Leg Press Heavy", "Lower", "Quads"),
    ("RDL Heavy", "Lower", "Hamstrings"),
]
