import type { NutritionPageData } from "@/types/nutrition";

export const nutritionPageMock: NutritionPageData = {
  heroLabel: "Fuel with intent",
  heroTitle: "Nutrition",
  heroDescription:
    "Your meal plan should feel controlled, repeatable, and easy to execute even when the day gets noisy. Pick fast, log clean, stay inside the cut.",
  mealPlan: [
    {
      id: "pre-workout",
      name: "Pre-workout",
      timing: "06:15 AM",
      selectedOptionId: "banana-whey-shot",
      options: [
        {
          id: "banana-whey-shot",
          title: "Banana + whey shot",
          subtitle: "Fast digesting and low-friction before morning training.",
          recipeId: "banana-whey-shot",
          tags: ["fast", "whey"],
          macros: { calories: 220, protein: 27, carbs: 22, fats: 2, fiber: 3 },
        },
        {
          id: "dates-coffee",
          title: "Dates + black coffee",
          subtitle: "Minimal calories with quick energy if appetite is low.",
          recipeId: "dates-coffee",
          tags: ["quick", "light"],
          macros: { calories: 150, protein: 2, carbs: 34, fats: 0, fiber: 2 },
        },
      ],
    },
    {
      id: "breakfast",
      name: "Breakfast",
      timing: "08:30 AM",
      selectedOptionId: "egg-oats-bowl",
      options: [
        {
          id: "egg-oats-bowl",
          title: "Egg oats power bowl",
          subtitle: "Protein-led breakfast with stable energy through the morning.",
          recipeId: "egg-oats-bowl",
          tags: ["egg", "high-protein"],
          macros: { calories: 420, protein: 31, carbs: 42, fats: 13, fiber: 8 },
        },
        {
          id: "paneer-toast-stack",
          title: "Paneer toast stack",
          subtitle: "A higher-satiety swap if hunger is stronger than usual.",
          recipeId: "paneer-toast-stack",
          tags: ["vegetarian", "savory"],
          macros: { calories: 455, protein: 29, carbs: 36, fats: 18, fiber: 7 },
        },
      ],
    },
    {
      id: "lunch",
      name: "Lunch",
      timing: "01:00 PM",
      selectedOptionId: "chicken-rice-box",
      options: [
        {
          id: "chicken-rice-box",
          title: "Chicken rice box",
          subtitle: "Lean protein, rice, and vegetables for the core meal.",
          recipeId: "chicken-rice-box",
          tags: ["high-protein", "meal-prep"],
          macros: { calories: 540, protein: 48, carbs: 56, fats: 12, fiber: 7 },
        },
        {
          id: "soya-bhurji-rice",
          title: "Soya bhurji rice",
          subtitle: "Budget-friendly vegetarian option with a strong protein floor.",
          recipeId: "soya-bhurji-rice",
          tags: ["soya", "vegetarian", "spicy"],
          macros: { calories: 500, protein: 39, carbs: 52, fats: 14, fiber: 9 },
        },
      ],
    },
    {
      id: "snack",
      name: "Snack",
      timing: "05:00 PM",
      selectedOptionId: "beast-life-whey",
      options: [
        {
          id: "beast-life-whey",
          title: "Beast Life Whey Protein",
          subtitle: "Fastest way to close the protein gap without clutter.",
          recipeId: "beast-life-whey",
          tags: ["whey", "quick-add"],
          macros: { calories: 130, protein: 25, carbs: 3, fats: 2, fiber: 0 },
        },
        {
          id: "hung-curd-chaat",
          title: "Hung curd chaat",
          subtitle: "Cooler, higher-volume snack for hunger-heavy afternoons.",
          recipeId: "hung-curd-chaat",
          tags: ["spicy", "vegetarian"],
          macros: { calories: 210, protein: 18, carbs: 14, fats: 8, fiber: 4 },
        },
      ],
    },
    {
      id: "dinner",
      name: "Dinner",
      timing: "08:45 PM",
      selectedOptionId: "fish-roti-plate",
      options: [
        {
          id: "fish-roti-plate",
          title: "Fish roti plate",
          subtitle: "Lean dinner that closes the day without calorie spillover.",
          recipeId: "fish-roti-plate",
          tags: ["lean", "savory"],
          macros: { calories: 470, protein: 43, carbs: 38, fats: 13, fiber: 6 },
        },
        {
          id: "paneer-salad-wrap",
          title: "Paneer salad wrap",
          subtitle: "Higher-volume fallback for a more flexible evening.",
          recipeId: "paneer-salad-wrap",
          tags: ["vegetarian", "high-volume"],
          macros: { calories: 440, protein: 32, carbs: 31, fats: 18, fiber: 7 },
        },
      ],
    },
  ],
  recipes: {
    "banana-whey-shot": {
      id: "banana-whey-shot",
      title: "Banana + whey shot",
      description: "The simplest clean pre-workout when the goal is energy without digestive drag.",
      ingredients: ["1 medium banana", "1 scoop Beast Life Whey Protein", "250 ml cold water", "2 ice cubes"],
      steps: ["Add water and whey to a shaker.", "Shake hard for 15 seconds.", "Eat the banana alongside the shake."],
      macros: { calories: 220, protein: 27, carbs: 22, fats: 2, fiber: 3 },
      portionNote: "Ideal 25 to 35 minutes before the first session.",
      tags: ["whey", "quick", "pre-workout"],
    },
    "dates-coffee": {
      id: "dates-coffee",
      title: "Dates + black coffee",
      description: "Ultra-light fallback when you want almost no prep and just enough fuel to train.",
      ingredients: ["3 Medjool dates", "1 cup black coffee"],
      steps: ["Pour the coffee fresh.", "Eat the dates slowly while the coffee cools.", "Start training within 15 minutes."],
      macros: { calories: 150, protein: 2, carbs: 34, fats: 0, fiber: 2 },
      portionNote: "Use on low-appetite mornings only.",
      tags: ["light", "quick"],
    },
    "egg-oats-bowl": {
      id: "egg-oats-bowl",
      title: "Egg oats power bowl",
      description: "A dense but clean breakfast built around satiety and recovery.",
      ingredients: ["60 g rolled oats", "3 whole eggs", "150 g egg whites", "1 tsp ghee", "Salt, chilli flakes, coriander"],
      steps: ["Cook oats in water with a pinch of salt.", "Scramble eggs and egg whites in ghee until softly set.", "Fold the eggs over the oats and finish with coriander and chilli flakes."],
      macros: { calories: 420, protein: 31, carbs: 42, fats: 13, fiber: 8 },
      portionNote: "Add cucumber on the side if you want more volume.",
      tags: ["egg", "high-protein"],
    },
    "paneer-toast-stack": {
      id: "paneer-toast-stack",
      title: "Paneer toast stack",
      description: "A portable vegetarian breakfast that still lands enough protein.",
      ingredients: ["120 g low-fat paneer", "3 slices whole wheat bread", "Mint chutney", "Onion, tomato, chilli"],
      steps: ["Crumble paneer with chopped onion, tomato, and chilli.", "Toast the bread lightly.", "Layer paneer mix with a thin spread of mint chutney."],
      macros: { calories: 455, protein: 29, carbs: 36, fats: 18, fiber: 7 },
      portionNote: "Best on days with longer gaps before lunch.",
      tags: ["vegetarian", "savory"],
    },
    "chicken-rice-box": {
      id: "chicken-rice-box",
      title: "Chicken rice box",
      description: "The dependable core lunch for cutting without guesswork.",
      ingredients: ["180 g grilled chicken breast", "180 g cooked rice", "150 g sauteed mixed vegetables", "1 tsp olive oil", "Dry spice rub"],
      steps: ["Season and grill the chicken until cooked through.", "Reheat the rice and vegetables.", "Assemble in a meal-prep box and finish with the spice rub."],
      macros: { calories: 540, protein: 48, carbs: 56, fats: 12, fiber: 7 },
      portionNote: "If steps are low for the day, reduce rice by 30 g cooked.",
      tags: ["meal-prep", "high-protein"],
    },
    "soya-bhurji-rice": {
      id: "soya-bhurji-rice",
      title: "Soya bhurji rice",
      description: "A spicy vegetarian lunch that keeps protein respectable without pushing calories too high.",
      ingredients: ["70 g dry soya chunks", "160 g cooked rice", "Onion, tomato, ginger, chilli", "1 tsp oil", "Turmeric, chilli powder, garam masala"],
      steps: ["Soak and squeeze the soya chunks.", "Cook aromatics and spices in oil.", "Add chopped soya, cook until dry, then serve over rice."],
      macros: { calories: 500, protein: 39, carbs: 52, fats: 14, fiber: 9 },
      portionNote: "Works well when you want a vegetarian lunch without losing bite.",
      tags: ["soya", "vegetarian", "spicy"],
    },
    "beast-life-whey": {
      id: "beast-life-whey",
      title: "Beast Life Whey Protein",
      description: "The fastest one-click protein insurance policy in the plan.",
      ingredients: ["1 scoop Beast Life Whey Protein", "250 ml water"],
      steps: ["Add water to the shaker.", "Add one scoop whey.", "Shake until fully dissolved."],
      macros: { calories: 130, protein: 25, carbs: 3, fats: 2, fiber: 0 },
      portionNote: "Use when protein is behind pace or post-workout speed matters.",
      tags: ["whey", "quick-add"],
    },
    "hung-curd-chaat": {
      id: "hung-curd-chaat",
      title: "Hung curd chaat",
      description: "A spicy evening snack that feels like food, not a compromise.",
      ingredients: ["180 g hung curd", "Cucumber", "Tomato", "Onion", "Roasted jeera", "Chaat masala", "Green chilli"],
      steps: ["Mix hung curd with roasted jeera and chaat masala.", "Fold in chopped vegetables and green chilli.", "Serve chilled with extra masala on top."],
      macros: { calories: 210, protein: 18, carbs: 14, fats: 8, fiber: 4 },
      portionNote: "Use on evenings when appetite is high but calories are tight.",
      tags: ["spicy", "vegetarian"],
    },
    "fish-roti-plate": {
      id: "fish-roti-plate",
      title: "Fish roti plate",
      description: "Lean, steady, and easy to repeat for a controlled dinner.",
      ingredients: ["170 g white fish fillet", "2 rotis", "150 g sauteed vegetables", "1 tsp oil", "Lemon, chilli, garlic"],
      steps: ["Marinate fish with lemon, garlic, and chilli.", "Pan-sear with minimal oil until flaky.", "Serve with rotis and vegetables."],
      macros: { calories: 470, protein: 43, carbs: 38, fats: 13, fiber: 6 },
      portionNote: "A clean dinner on training days when protein still matters.",
      tags: ["lean", "dinner"],
    },
    "paneer-salad-wrap": {
      id: "paneer-salad-wrap",
      title: "Paneer salad wrap",
      description: "A more flexible vegetarian dinner with good satiety.",
      ingredients: ["120 g paneer", "2 wraps", "Lettuce", "Cucumber", "Onion", "Yogurt mint spread"],
      steps: ["Pan-sear paneer cubes lightly.", "Warm the wraps.", "Layer salad, paneer, and yogurt spread, then roll tight."],
      macros: { calories: 440, protein: 32, carbs: 31, fats: 18, fiber: 7 },
      portionNote: "Best used when dinner needs to feel higher-volume.",
      tags: ["vegetarian", "high-volume"],
    },
  },
  quickAdds: [
    {
      id: "quick-whey",
      title: "Beast Life Whey Protein",
      description: "1 scoop, water only, fast protein close.",
      mealType: "breakfast",
      macros: { calories: 130, protein: 25, carbs: 3, fats: 2, fiber: 0 },
      tags: ["whey", "quick-add"],
    },
    {
      id: "spicy-makhana",
      title: "Spicy evening makhana",
      description: "Roasted foxnuts with chilli, salt, and lime.",
      mealType: "snack",
      macros: { calories: 145, protein: 5, carbs: 24, fats: 3, fiber: 2 },
      tags: ["spicy", "snack"],
    },
    {
      id: "masala-corn-cup",
      title: "Masala sweet corn cup",
      description: "Hot corn with lemon, chilli, and black salt.",
      mealType: "snack",
      macros: { calories: 160, protein: 5, carbs: 28, fats: 2, fiber: 4 },
      tags: ["spicy", "vegetarian"],
    },
  ],
  summary: {
    caloriesConsumed: 1680,
    caloriesTarget: 2200,
    proteinConsumed: 142,
    proteinTarget: 165,
    remainingCalories: 520,
    remainingProtein: 23,
    macroProgress: [
      { label: "Calories", consumed: 1680, target: 2200, unit: "kcal", tone: "primary" },
      { label: "Protein", consumed: 142, target: 165, unit: "g", tone: "secondary" },
      { label: "Carbs", consumed: 172, target: 210, unit: "g" },
      { label: "Fats", consumed: 51, target: 70, unit: "g", tone: "warning" },
      { label: "Fiber", consumed: 24, target: 32, unit: "g", tone: "secondary" },
    ],
  },
  energyBalance: {
    maintenanceCalories: 2680,
    targetCalories: 2200,
    foodCalories: 1680,
    exerciseCaloriesBurned: 310,
    netCalories: 1370,
    statusLabel: "Deficit -830 kcal",
    statusTone: "success",
    description: "The day is sitting in a strong deficit. Keep dinner controlled and use training calories without chasing them back.",
  },
  mealLog: [
    { id: "1", time: "06:20 AM", mealLabel: "Pre-workout", title: "Banana + whey shot", calories: 220, protein: 27, note: "Low-friction start before push session." },
    { id: "2", time: "08:45 AM", mealLabel: "Breakfast", title: "Egg oats power bowl", calories: 420, protein: 31, note: "Held satiety through late morning." },
    { id: "3", time: "01:10 PM", mealLabel: "Lunch", title: "Chicken rice box", calories: 540, protein: 48, note: "Core plan meal, no swaps needed." },
    { id: "4", time: "05:05 PM", mealLabel: "Snack", title: "Beast Life Whey Protein", calories: 130, protein: 25, note: "Closed the afternoon protein dip quickly." },
    { id: "5", time: "08:50 PM", mealLabel: "Dinner", title: "Fish roti plate", calories: 470, protein: 43, note: "Dinner selected for a lean close to the day." },
  ],
};
