import type { TodaySummary } from "@/types/today";

export const todaySummaryMock: TodaySummary = {
  dayNumber: 42,
  totalDays: 75,
  completionPercentage: 62,
  currentStreak: 11,
  perfectDays: 28,
  failedDays: 3,
  completedCount: 5,
  pendingCount: 3,
  heroCopy:
    "Discipline looks quiet when it is working. Today is about stacking one more clean day across training, diet, water, and proof.",
  quickActions: ["Log workout", "Add 500 ml", "Open meal plan"],
  notes:
    "Protect the evening. Water, second session, and progress photo are the only things that can still steal the day.",
  focusLabel: "Execution window",
  splitLabel: "Pull + outdoor walk",
  hydrationLiters: 2.6,
  hydrationTargetLiters: 4,
  calories: 1680,
  caloriesTarget: 2200,
  protein: 142,
  complianceScore: 84,
  totalSessions: 1,
  workoutSessions: 1,
  cardioSessions: 0,
  outdoorSessions: 0,
  photoCount: 1,
  pendingTasks: ["Outdoor workout", "Water goal"],
  dayStatus: "incomplete",
  tasks: [
    {
      id: "workout-1",
      title: "Workout 1",
      description: "Primary strength session logged with full intent.",
      category: "Training",
      status: "completed",
      accent: "primary",
      interaction: "navigate",
      actionLabel: "Open workout log",
      navigateTo: "/workouts",
      field: "workout_1_completed",
    },
    {
      id: "outdoor-workout",
      title: "Outdoor workout",
      description: "At least one session must be completed outside.",
      category: "Challenge",
      status: "pending",
      accent: "secondary",
      interaction: "navigate",
      actionLabel: "Open cardio",
      navigateTo: "/cardio",
      field: "one_workout_outdoors",
    },
    {
      id: "followed-diet",
      title: "Followed diet",
      description: "Meals stayed aligned with the calorie-deficit plan.",
      category: "Nutrition",
      status: "completed",
      accent: "primary",
      interaction: "toggle",
      pendingActionLabel: "Mark diet followed",
      completedActionLabel: "Mark diet not followed",
      field: "followed_diet",
    },
    {
      id: "no-cheat-meal",
      title: "No cheat meal",
      description: "Zero off-plan meals so far today.",
      category: "Nutrition",
      status: "completed",
      accent: "primary",
      interaction: "toggle",
      pendingActionLabel: "Mark no cheat meal",
      completedActionLabel: "Mark cheat meal happened",
      field: "no_cheat_meals",
    },
    {
      id: "water-goal",
      title: "Water goal",
      description: "1.4L remaining before the day closes out.",
      category: "Hydration",
      status: "pending",
      accent: "secondary",
      interaction: "navigate",
      actionLabel: "Open hydration",
      navigateTo: "/hydration",
      field: "water_goal_completed",
    },
    {
      id: "progress-photo",
      title: "Progress photo",
      description: "Capture the daily proof shot before bed.",
      category: "Accountability",
      status: "completed",
      accent: "primary",
      interaction: "navigate",
      actionLabel: "Open progress photos",
      navigateTo: "/progress-photos",
      field: "progress_picture_taken",
    },
  ],
};
